7. Hyperparameter Tuning of Random Forest
Dataset: Adult Income Dataset
Download:

https://www.kaggle.com/datasets/uciml/adult-census-income

Tasks
Perform Grid Search on:

n_estimators:
50
100
200


max_depth:
5
10
20
None


max_features:
sqrt
log2

Find the best model.

Report:

Best Parameters

Best Cross Validation Score

Test Accuracy

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('adult.csv')
df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [3]:
# convert categorical coumns

df = pd.get_dummies(df, drop_first=True)

df.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native.country_Puerto-Rico,native.country_Scotland,native.country_South,native.country_Taiwan,native.country_Thailand,native.country_Trinadad&Tobago,native.country_United-States,native.country_Vietnam,native.country_Yugoslavia,income_>50K
0,90,77053,9,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,82,132870,9,0,4356,18,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
2,66,186061,10,0,4356,40,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,54,140359,4,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
4,41,264663,10,0,3900,40,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False

In [4]:
X = df.drop("income_>50K", axis=1)

y = df["income_>50K"]

In [5]:
# train - test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
rf = RandomForestClassifier(random_state=42)

In [7]:

#Creating Parameter Grid

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [5, 10, 20, None],
    "max_features": ["sqrt", "log2"]
}

In [8]:
grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [9]:
# Cross Validation

print("Best Cross Validation Score:")

print(round(grid.best_score_,4))

Best Cross Validation Score:
0.8629

In [10]:
best_model = grid.best_estimator_

prediction = best_model.predict(X_test)

accuracy = accuracy_score(y_test, prediction)

print("Test Accuracy:")

print(round(accuracy,4))

Test Accuracy:
0.8614

In [11]:
print("========== FINAL RESULT ==========\n")

print("Best Parameters:")
print(grid.best_params_)

print()

print("Best Cross Validation Score:")
print(round(grid.best_score_,4))

print()

print("Test Accuracy:")
print(round(accuracy,4))

========== FINAL RESULT ==========

Best Parameters:
{'max_depth': 20, 'max_features': 'sqrt', 'n_estimators': 200}

Best Cross Validation Score:
0.8629

Test Accuracy:
0.8614