Problem 4: Heart Disease Prediction

Dataset: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction

Objective

Predict whether a patient has heart disease.
Tasks

Train four SVM models:

Linear

Polynomial

RBF

Sigmoid

Compare

Accuracy

Precision

Recall

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [2]:
df = pd.read_csv("heart.csv")

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
encoder = LabelEncoder()

for column in df.columns:
    if df[column].dtype == "object":
        df[column] = encoder.fit_transform(df[column])

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [4]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [7]:
models = {
    "Linear": SVC(kernel="linear"),
    "Polynomial": SVC(kernel="poly"),
    "RBF": SVC(kernel="rbf"),
    "Sigmoid": SVC(kernel="sigmoid")
}

In [8]:
results = []


for name,model in models.items():
  model.fit(X_train,y_train)

  y_pred = model.predict(X_test)

In [9]:
accuracy = accuracy_score(y_test,y_pred)
precison = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)



results.append( [
    name,
    round(accuracy,4),
    round(accuracy,4),
    round(accuracy,4)
])

In [10]:
comparison = pd.DataFrame(
    results,
    columns=[
        "Kernel",
        "Accuracy",
        "Precision",
        "Recall"
    ]
)

comparison

    Kernel  Accuracy  Precision  Recall
0  Sigmoid    0.8207     0.8207  0.8207

In [11]:
best = comparison.loc[
    comparison["Accuracy"].idxmax()
]

print(best)

Kernel       Sigmoid
Accuracy      0.8207
Precision     0.8207
Recall        0.8207
Name: 0, dtype: object